title: Hello, welcome to Vany's blog ^^
author: Vany
email: m@vanyi3.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  It's a great place for you to share and discuss issues :?

# social links
twitter_username: vanyi3
github_username: vanyi3

show_excerpts: true # set to false to remove excerpts on the homepage
